import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionWraper from "./api/sessionWraper/sessionWrap";
import NextTopLoader from "nextjs-toploader";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body className={`antialiased min-h-screen bg-[#E4E0E1]`}>
        <NextTopLoader />
        <ToastContainer position="top-center" theme="colored" />
        <SessionWraper>{children}</SessionWraper>
      </body>
    </html>
  );
}
